; ModuleID = './code/033-16155vbetables-gen.c'
source_filename = "./code/033-16155vbetables-gen.c"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx14.0.0"

%struct.ModeInfo = type { i32, i32, i32, i32 }

@modes = global [37 x %struct.ModeInfo] [%struct.ModeInfo { i32 640, i32 400, i32 8, i32 256 }, %struct.ModeInfo { i32 640, i32 480, i32 8, i32 257 }, %struct.ModeInfo { i32 800, i32 600, i32 4, i32 258 }, %struct.ModeInfo { i32 800, i32 600, i32 8, i32 259 }, %struct.ModeInfo { i32 1024, i32 768, i32 4, i32 260 }, %struct.ModeInfo { i32 1024, i32 768, i32 8, i32 261 }, %struct.ModeInfo { i32 1280, i32 1024, i32 4, i32 262 }, %struct.ModeInfo { i32 1280, i32 1024, i32 8, i32 263 }, %struct.ModeInfo { i32 320, i32 200, i32 15, i32 269 }, %struct.ModeInfo { i32 320, i32 200, i32 16, i32 270 }, %struct.ModeInfo { i32 320, i32 200, i32 24, i32 271 }, %struct.ModeInfo { i32 640, i32 480, i32 15, i32 272 }, %struct.ModeInfo { i32 640, i32 480, i32 16, i32 273 }, %struct.ModeInfo { i32 640, i32 480, i32 24, i32 274 }, %struct.ModeInfo { i32 800, i32 600, i32 15, i32 275 }, %struct.ModeInfo { i32 800, i32 600, i32 16, i32 276 }, %struct.ModeInfo { i32 800, i32 600, i32 24, i32 277 }, %struct.ModeInfo { i32 1024, i32 768, i32 15, i32 278 }, %struct.ModeInfo { i32 1024, i32 768, i32 16, i32 279 }, %struct.ModeInfo { i32 1024, i32 768, i32 24, i32 280 }, %struct.ModeInfo { i32 1280, i32 1024, i32 15, i32 281 }, %struct.ModeInfo { i32 1280, i32 1024, i32 16, i32 282 }, %struct.ModeInfo { i32 1280, i32 1024, i32 24, i32 283 }, %struct.ModeInfo { i32 320, i32 200, i32 32, i32 320 }, %struct.ModeInfo { i32 640, i32 400, i32 32, i32 321 }, %struct.ModeInfo { i32 640, i32 480, i32 32, i32 322 }, %struct.ModeInfo { i32 800, i32 600, i32 32, i32 323 }, %struct.ModeInfo { i32 1024, i32 768, i32 32, i32 324 }, %struct.ModeInfo { i32 1280, i32 1024, i32 32, i32 325 }, %struct.ModeInfo { i32 320, i32 200, i32 8, i32 326 }, %struct.ModeInfo { i32 1600, i32 1200, i32 32, i32 327 }, %struct.ModeInfo { i32 1152, i32 864, i32 8, i32 328 }, %struct.ModeInfo { i32 1152, i32 864, i32 15, i32 329 }, %struct.ModeInfo { i32 1152, i32 864, i32 16, i32 330 }, %struct.ModeInfo { i32 1152, i32 864, i32 24, i32 331 }, %struct.ModeInfo { i32 1152, i32 864, i32 32, i32 332 }, %struct.ModeInfo zeroinitializer], align 4
@.str = private unnamed_addr constant [59 x i8] c"/* THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT */\0A\0A\00", align 1
@.str.1 = private unnamed_addr constant [45 x i8] c"#define VBE_DISPI_TOTAL_VIDEO_MEMORY_MB %d\0A\0A\00", align 1
@.str.2 = private unnamed_addr constant [43 x i8] c"static ModeInfoListItem mode_info_list[]=\0A\00", align 1
@.str.3 = private unnamed_addr constant [3 x i8] c"{\0A\00", align 1
@.str.4 = private unnamed_addr constant [26 x i8] c"{ 0x%04x, /* %dx%dx%d */\0A\00", align 1
@.str.5 = private unnamed_addr constant [33 x i8] c"{ /*Bit16u ModeAttributes*/ %s,\0A\00", align 1
@.str.6 = private unnamed_addr constant [186 x i8] c"VBE_MODE_ATTRIBUTE_SUPPORTED | VBE_MODE_ATTRIBUTE_EXTENDED_INFORMATION_AVAILABLE | VBE_MODE_ATTRIBUTE_COLOR_MODE | VBE_MODE_ATTRIBUTE_TTY_BIOS_SUPPORT | VBE_MODE_ATTRIBUTE_GRAPHICS_MODE\00", align 1
@.str.7 = private unnamed_addr constant [194 x i8] c"VBE_MODE_ATTRIBUTE_SUPPORTED | VBE_MODE_ATTRIBUTE_EXTENDED_INFORMATION_AVAILABLE | VBE_MODE_ATTRIBUTE_COLOR_MODE | VBE_MODE_ATTRIBUTE_LINEAR_FRAME_BUFFER_MODE | VBE_MODE_ATTRIBUTE_GRAPHICS_MODE\00", align 1
@.str.8 = private unnamed_addr constant [31 x i8] c"/*Bit8u  WinAAttributes*/ %s,\0A\00", align 1
@.str.9 = private unnamed_addr constant [98 x i8] c"VBE_WINDOW_ATTRIBUTE_RELOCATABLE | VBE_WINDOW_ATTRIBUTE_READABLE | VBE_WINDOW_ATTRIBUTE_WRITEABLE\00", align 1
@.str.10 = private unnamed_addr constant [31 x i8] c"/*Bit8u  WinBAttributes*/ %d,\0A\00", align 1
@.str.11 = private unnamed_addr constant [31 x i8] c"/*Bit16u WinGranularity*/ %s,\0A\00", align 1
@.str.12 = private unnamed_addr constant [23 x i8] c"VBE_DISPI_BANK_SIZE_KB\00", align 1
@.str.13 = private unnamed_addr constant [24 x i8] c"/*Bit16u WinSize*/ %s,\0A\00", align 1
@.str.14 = private unnamed_addr constant [28 x i8] c"/*Bit16u WinASegment*/ %s,\0A\00", align 1
@.str.15 = private unnamed_addr constant [13 x i8] c"VGAMEM_GRAPH\00", align 1
@.str.16 = private unnamed_addr constant [32 x i8] c"/*Bit16u WinBSegment*/ 0x%04x,\0A\00", align 1
@.str.17 = private unnamed_addr constant [27 x i8] c"/*Bit32u WinFuncPtr*/ %d,\0A\00", align 1
@.str.18 = private unnamed_addr constant [33 x i8] c"/*Bit16u BytesPerScanLine*/ %d,\0A\00", align 1
@.str.19 = private unnamed_addr constant [28 x i8] c"/*Bit16u XResolution*/ %d,\0A\00", align 1
@.str.20 = private unnamed_addr constant [28 x i8] c"/*Bit16u YResolution*/ %d,\0A\00", align 1
@.str.21 = private unnamed_addr constant [26 x i8] c"/*Bit8u  XCharSize*/ %d,\0A\00", align 1
@.str.22 = private unnamed_addr constant [26 x i8] c"/*Bit8u  YCharSize*/ %d,\0A\00", align 1
@.str.23 = private unnamed_addr constant [31 x i8] c"/*Bit8u  NumberOfPlanes*/ %d,\0A\00", align 1
@.str.24 = private unnamed_addr constant [29 x i8] c"/*Bit8u  BitsPerPixel*/ %d,\0A\00", align 1
@.str.25 = private unnamed_addr constant [30 x i8] c"/*Bit8u  NumberOfBanks*/ %d,\0A\00", align 1
@.str.26 = private unnamed_addr constant [23 x i8] c"VBE_MEMORYMODEL_PLANAR\00", align 1
@.str.27 = private unnamed_addr constant [29 x i8] c"VBE_MEMORYMODEL_PACKED_PIXEL\00", align 1
@.str.28 = private unnamed_addr constant [29 x i8] c"VBE_MEMORYMODEL_DIRECT_COLOR\00", align 1
@.str.29 = private unnamed_addr constant [28 x i8] c"/*Bit8u  MemoryModel*/ %s,\0A\00", align 1
@.str.30 = private unnamed_addr constant [25 x i8] c"/*Bit8u  BankSize*/ %d,\0A\00", align 1
@.str.31 = private unnamed_addr constant [35 x i8] c"/*Bit8u  NumberOfImagePages*/ %d,\0A\00", align 1
@.str.32 = private unnamed_addr constant [30 x i8] c"/*Bit8u  Reserved_page*/ %d,\0A\00", align 1
@.str.33 = private unnamed_addr constant [28 x i8] c"/*Bit8u  RedMaskSize*/ %d,\0A\00", align 1
@.str.34 = private unnamed_addr constant [33 x i8] c"/*Bit8u  RedFieldPosition*/ %d,\0A\00", align 1
@.str.35 = private unnamed_addr constant [30 x i8] c"/*Bit8u  GreenMaskSize*/ %d,\0A\00", align 1
@.str.36 = private unnamed_addr constant [35 x i8] c"/*Bit8u  GreenFieldPosition*/ %d,\0A\00", align 1
@.str.37 = private unnamed_addr constant [29 x i8] c"/*Bit8u  BlueMaskSize*/ %d,\0A\00", align 1
@.str.38 = private unnamed_addr constant [34 x i8] c"/*Bit8u  BlueFieldPosition*/ %d,\0A\00", align 1
@.str.39 = private unnamed_addr constant [29 x i8] c"/*Bit8u  RsvdMaskSize*/ %d,\0A\00", align 1
@.str.40 = private unnamed_addr constant [34 x i8] c"/*Bit8u  RsvdFieldPosition*/ %d,\0A\00", align 1
@.str.41 = private unnamed_addr constant [36 x i8] c"/*Bit8u  DirectColorModeInfo*/ %s,\0A\00", align 1
@.str.42 = private unnamed_addr constant [40 x i8] c"VBE_DIRECTCOLOR_RESERVED_BITS_AVAILABLE\00", align 1
@.str.43 = private unnamed_addr constant [2 x i8] c"0\00", align 1
@.str.44 = private unnamed_addr constant [28 x i8] c"/*Bit32u PhysBasePtr*/ %s,\0A\00", align 1
@.str.45 = private unnamed_addr constant [31 x i8] c"VBE_DISPI_LFB_PHYSICAL_ADDRESS\00", align 1
@.str.46 = private unnamed_addr constant [35 x i8] c"/*Bit32u OffScreenMemOffset*/ %d,\0A\00", align 1
@.str.47 = private unnamed_addr constant [33 x i8] c"/*Bit16u OffScreenMemSize*/ %d,\0A\00", align 1
@.str.48 = private unnamed_addr constant [36 x i8] c"/*Bit16u LinBytesPerScanLine*/ %d,\0A\00", align 1
@.str.49 = private unnamed_addr constant [33 x i8] c"/*Bit8u  BnkNumberOfPages*/ %d,\0A\00", align 1
@.str.50 = private unnamed_addr constant [33 x i8] c"/*Bit8u  LinNumberOfPages*/ %d,\0A\00", align 1
@.str.51 = private unnamed_addr constant [31 x i8] c"/*Bit8u  LinRedMaskSize*/ %d,\0A\00", align 1
@.str.52 = private unnamed_addr constant [36 x i8] c"/*Bit8u  LinRedFieldPosition*/ %d,\0A\00", align 1
@.str.53 = private unnamed_addr constant [33 x i8] c"/*Bit8u  LinGreenMaskSize*/ %d,\0A\00", align 1
@.str.54 = private unnamed_addr constant [38 x i8] c"/*Bit8u  LinGreenFieldPosition*/ %d,\0A\00", align 1
@.str.55 = private unnamed_addr constant [32 x i8] c"/*Bit8u  LinBlueMaskSize*/ %d,\0A\00", align 1
@.str.56 = private unnamed_addr constant [37 x i8] c"/*Bit8u  LinBlueFieldPosition*/ %d,\0A\00", align 1
@.str.57 = private unnamed_addr constant [32 x i8] c"/*Bit8u  LinRsvdMaskSize*/ %d,\0A\00", align 1
@.str.58 = private unnamed_addr constant [37 x i8] c"/*Bit8u  LinRsvdFieldPosition*/ %d,\0A\00", align 1
@.str.59 = private unnamed_addr constant [30 x i8] c"/*Bit32u MaxPixelClock*/ %d,\0A\00", align 1
@.str.60 = private unnamed_addr constant [6 x i8] c"} },\0A\00", align 1
@.str.61 = private unnamed_addr constant [30 x i8] c"{ VBE_VESA_MODE_END_OF_LIST,\0A\00", align 1
@.str.62 = private unnamed_addr constant [6 x i8] c"{ 0,\0A\00", align 1
@.str.63 = private unnamed_addr constant [4 x i8] c"};\0A\00", align 1

; Function Attrs: noinline nounwind optnone ssp uwtable(sync)
define i32 @main(i32 noundef %argc, ptr noundef %argv) #0 {
entry:
  %retval = alloca i32, align 4
  %argc.addr = alloca i32, align 4
  %argv.addr = alloca ptr, align 8
  %pm = alloca ptr, align 8
  %pages = alloca i32, align 4
  %pitch = alloca i32, align 4
  %r_size = alloca i32, align 4
  %r_pos = alloca i32, align 4
  %g_size = alloca i32, align 4
  %g_pos = alloca i32, align 4
  %b_size = alloca i32, align 4
  %b_pos = alloca i32, align 4
  %a_size = alloca i32, align 4
  %a_pos = alloca i32, align 4
  %str = alloca ptr, align 8
  %vram_size = alloca i64, align 8
  store i32 0, ptr %retval, align 4
  store i32 %argc, ptr %argc.addr, align 4
  store ptr %argv, ptr %argv.addr, align 8
  store i64 8388608, ptr %vram_size, align 8
  %call = call i32 (ptr, ...) @printf(ptr noundef @.str)
  %call1 = call i32 (ptr, ...) @printf(ptr noundef @.str.1, i32 noundef 8)
  %call2 = call i32 (ptr, ...) @printf(ptr noundef @.str.2)
  %call3 = call i32 (ptr, ...) @printf(ptr noundef @.str.3)
  store ptr @modes, ptr %pm, align 8
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load ptr, ptr %pm, align 8
  %mode = getelementptr inbounds %struct.ModeInfo, ptr %0, i32 0, i32 3
  %1 = load i32, ptr %mode, align 4
  %cmp = icmp ne i32 %1, 0
  br i1 %cmp, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %2 = load ptr, ptr %pm, align 8
  %depth = getelementptr inbounds %struct.ModeInfo, ptr %2, i32 0, i32 2
  %3 = load i32, ptr %depth, align 4
  %cmp4 = icmp eq i32 %3, 4
  br i1 %cmp4, label %if.then, label %if.else

if.then:                                          ; preds = %for.body
  %4 = load ptr, ptr %pm, align 8
  %width = getelementptr inbounds %struct.ModeInfo, ptr %4, i32 0, i32 0
  %5 = load i32, ptr %width, align 4
  %add = add nsw i32 %5, 7
  %div = sdiv i32 %add, 8
  store i32 %div, ptr %pitch, align 4
  br label %if.end

if.else:                                          ; preds = %for.body
  %6 = load ptr, ptr %pm, align 8
  %width5 = getelementptr inbounds %struct.ModeInfo, ptr %6, i32 0, i32 0
  %7 = load i32, ptr %width5, align 4
  %8 = load ptr, ptr %pm, align 8
  %depth6 = getelementptr inbounds %struct.ModeInfo, ptr %8, i32 0, i32 2
  %9 = load i32, ptr %depth6, align 4
  %add7 = add nsw i32 %9, 7
  %div8 = sdiv i32 %add7, 8
  %mul = mul nsw i32 %7, %div8
  store i32 %mul, ptr %pitch, align 4
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %10 = load i64, ptr %vram_size, align 8
  %11 = load ptr, ptr %pm, align 8
  %height = getelementptr inbounds %struct.ModeInfo, ptr %11, i32 0, i32 1
  %12 = load i32, ptr %height, align 4
  %13 = load i32, ptr %pitch, align 4
  %mul9 = mul nsw i32 %12, %13
  %conv = sext i32 %mul9 to i64
  %div10 = sdiv i64 %10, %conv
  %conv11 = trunc i64 %div10 to i32
  store i32 %conv11, ptr %pages, align 4
  %14 = load i32, ptr %pages, align 4
  %cmp12 = icmp sgt i32 %14, 0
  br i1 %cmp12, label %if.then14, label %if.end121

if.then14:                                        ; preds = %if.end
  %15 = load ptr, ptr %pm, align 8
  %mode15 = getelementptr inbounds %struct.ModeInfo, ptr %15, i32 0, i32 3
  %16 = load i32, ptr %mode15, align 4
  %17 = load ptr, ptr %pm, align 8
  %width16 = getelementptr inbounds %struct.ModeInfo, ptr %17, i32 0, i32 0
  %18 = load i32, ptr %width16, align 4
  %19 = load ptr, ptr %pm, align 8
  %height17 = getelementptr inbounds %struct.ModeInfo, ptr %19, i32 0, i32 1
  %20 = load i32, ptr %height17, align 4
  %21 = load ptr, ptr %pm, align 8
  %depth18 = getelementptr inbounds %struct.ModeInfo, ptr %21, i32 0, i32 2
  %22 = load i32, ptr %depth18, align 4
  %call19 = call i32 (ptr, ...) @printf(ptr noundef @.str.4, i32 noundef %16, i32 noundef %18, i32 noundef %20, i32 noundef %22)
  %23 = load ptr, ptr %pm, align 8
  %depth20 = getelementptr inbounds %struct.ModeInfo, ptr %23, i32 0, i32 2
  %24 = load i32, ptr %depth20, align 4
  %cmp21 = icmp eq i32 %24, 4
  br i1 %cmp21, label %if.then23, label %if.else25

if.then23:                                        ; preds = %if.then14
  %call24 = call i32 (ptr, ...) @printf(ptr noundef @.str.5, ptr noundef @.str.6)
  br label %if.end27

if.else25:                                        ; preds = %if.then14
  %call26 = call i32 (ptr, ...) @printf(ptr noundef @.str.5, ptr noundef @.str.7)
  br label %if.end27

if.end27:                                         ; preds = %if.else25, %if.then23
  %call28 = call i32 (ptr, ...) @printf(ptr noundef @.str.8, ptr noundef @.str.9)
  %call29 = call i32 (ptr, ...) @printf(ptr noundef @.str.10, i32 noundef 0)
  %call30 = call i32 (ptr, ...) @printf(ptr noundef @.str.11, ptr noundef @.str.12)
  %call31 = call i32 (ptr, ...) @printf(ptr noundef @.str.13, ptr noundef @.str.12)
  %call32 = call i32 (ptr, ...) @printf(ptr noundef @.str.14, ptr noundef @.str.15)
  %call33 = call i32 (ptr, ...) @printf(ptr noundef @.str.16, i32 noundef 0)
  %call34 = call i32 (ptr, ...) @printf(ptr noundef @.str.17, i32 noundef 0)
  %25 = load i32, ptr %pitch, align 4
  %call35 = call i32 (ptr, ...) @printf(ptr noundef @.str.18, i32 noundef %25)
  %26 = load ptr, ptr %pm, align 8
  %width36 = getelementptr inbounds %struct.ModeInfo, ptr %26, i32 0, i32 0
  %27 = load i32, ptr %width36, align 4
  %call37 = call i32 (ptr, ...) @printf(ptr noundef @.str.19, i32 noundef %27)
  %28 = load ptr, ptr %pm, align 8
  %height38 = getelementptr inbounds %struct.ModeInfo, ptr %28, i32 0, i32 1
  %29 = load i32, ptr %height38, align 4
  %call39 = call i32 (ptr, ...) @printf(ptr noundef @.str.20, i32 noundef %29)
  %call40 = call i32 (ptr, ...) @printf(ptr noundef @.str.21, i32 noundef 8)
  %call41 = call i32 (ptr, ...) @printf(ptr noundef @.str.22, i32 noundef 16)
  %30 = load ptr, ptr %pm, align 8
  %depth42 = getelementptr inbounds %struct.ModeInfo, ptr %30, i32 0, i32 2
  %31 = load i32, ptr %depth42, align 4
  %cmp43 = icmp eq i32 %31, 4
  br i1 %cmp43, label %if.then45, label %if.else47

if.then45:                                        ; preds = %if.end27
  %call46 = call i32 (ptr, ...) @printf(ptr noundef @.str.23, i32 noundef 4)
  br label %if.end49

if.else47:                                        ; preds = %if.end27
  %call48 = call i32 (ptr, ...) @printf(ptr noundef @.str.23, i32 noundef 1)
  br label %if.end49

if.end49:                                         ; preds = %if.else47, %if.then45
  %32 = load ptr, ptr %pm, align 8
  %depth50 = getelementptr inbounds %struct.ModeInfo, ptr %32, i32 0, i32 2
  %33 = load i32, ptr %depth50, align 4
  %call51 = call i32 (ptr, ...) @printf(ptr noundef @.str.24, i32 noundef %33)
  %call52 = call i32 (ptr, ...) @printf(ptr noundef @.str.25, i32 noundef 1)
  %34 = load ptr, ptr %pm, align 8
  %depth53 = getelementptr inbounds %struct.ModeInfo, ptr %34, i32 0, i32 2
  %35 = load i32, ptr %depth53, align 4
  %cmp54 = icmp eq i32 %35, 4
  br i1 %cmp54, label %if.then56, label %if.else57

if.then56:                                        ; preds = %if.end49
  store ptr @.str.26, ptr %str, align 8
  br label %if.end64

if.else57:                                        ; preds = %if.end49
  %36 = load ptr, ptr %pm, align 8
  %depth58 = getelementptr inbounds %struct.ModeInfo, ptr %36, i32 0, i32 2
  %37 = load i32, ptr %depth58, align 4
  %cmp59 = icmp eq i32 %37, 8
  br i1 %cmp59, label %if.then61, label %if.else62

if.then61:                                        ; preds = %if.else57
  store ptr @.str.27, ptr %str, align 8
  br label %if.end63

if.else62:                                        ; preds = %if.else57
  store ptr @.str.28, ptr %str, align 8
  br label %if.end63

if.end63:                                         ; preds = %if.else62, %if.then61
  br label %if.end64

if.end64:                                         ; preds = %if.end63, %if.then56
  %38 = load ptr, ptr %str, align 8
  %call65 = call i32 (ptr, ...) @printf(ptr noundef @.str.29, ptr noundef %38)
  %call66 = call i32 (ptr, ...) @printf(ptr noundef @.str.30, i32 noundef 0)
  %39 = load ptr, ptr %pm, align 8
  %depth67 = getelementptr inbounds %struct.ModeInfo, ptr %39, i32 0, i32 2
  %40 = load i32, ptr %depth67, align 4
  %cmp68 = icmp eq i32 %40, 4
  br i1 %cmp68, label %if.then70, label %if.else73

if.then70:                                        ; preds = %if.end64
  %41 = load i32, ptr %pages, align 4
  %div71 = sdiv i32 %41, 4
  %sub = sub nsw i32 %div71, 1
  %call72 = call i32 (ptr, ...) @printf(ptr noundef @.str.31, i32 noundef %sub)
  br label %if.end76

if.else73:                                        ; preds = %if.end64
  %42 = load i32, ptr %pages, align 4
  %sub74 = sub nsw i32 %42, 1
  %call75 = call i32 (ptr, ...) @printf(ptr noundef @.str.31, i32 noundef %sub74)
  br label %if.end76

if.end76:                                         ; preds = %if.else73, %if.then70
  %call77 = call i32 (ptr, ...) @printf(ptr noundef @.str.32, i32 noundef 0)
  %43 = load ptr, ptr %pm, align 8
  %depth78 = getelementptr inbounds %struct.ModeInfo, ptr %43, i32 0, i32 2
  %44 = load i32, ptr %depth78, align 4
  switch i32 %44, label %sw.default [
    i32 15, label %sw.bb
    i32 16, label %sw.bb79
    i32 24, label %sw.bb80
    i32 32, label %sw.bb81
  ]

sw.bb:                                            ; preds = %if.end76
  store i32 5, ptr %r_size, align 4
  store i32 10, ptr %r_pos, align 4
  store i32 5, ptr %g_size, align 4
  store i32 5, ptr %g_pos, align 4
  store i32 5, ptr %b_size, align 4
  store i32 0, ptr %b_pos, align 4
  store i32 1, ptr %a_size, align 4
  store i32 15, ptr %a_pos, align 4
  br label %sw.epilog

sw.bb79:                                          ; preds = %if.end76
  store i32 5, ptr %r_size, align 4
  store i32 11, ptr %r_pos, align 4
  store i32 6, ptr %g_size, align 4
  store i32 5, ptr %g_pos, align 4
  store i32 5, ptr %b_size, align 4
  store i32 0, ptr %b_pos, align 4
  store i32 0, ptr %a_size, align 4
  store i32 0, ptr %a_pos, align 4
  br label %sw.epilog

sw.bb80:                                          ; preds = %if.end76
  store i32 8, ptr %r_size, align 4
  store i32 16, ptr %r_pos, align 4
  store i32 8, ptr %g_size, align 4
  store i32 8, ptr %g_pos, align 4
  store i32 8, ptr %b_size, align 4
  store i32 0, ptr %b_pos, align 4
  store i32 0, ptr %a_size, align 4
  store i32 0, ptr %a_pos, align 4
  br label %sw.epilog

sw.bb81:                                          ; preds = %if.end76
  store i32 8, ptr %r_size, align 4
  store i32 16, ptr %r_pos, align 4
  store i32 8, ptr %g_size, align 4
  store i32 8, ptr %g_pos, align 4
  store i32 8, ptr %b_size, align 4
  store i32 0, ptr %b_pos, align 4
  store i32 8, ptr %a_size, align 4
  store i32 24, ptr %a_pos, align 4
  br label %sw.epilog

sw.default:                                       ; preds = %if.end76
  store i32 0, ptr %r_size, align 4
  store i32 0, ptr %r_pos, align 4
  store i32 0, ptr %g_size, align 4
  store i32 0, ptr %g_pos, align 4
  store i32 0, ptr %b_size, align 4
  store i32 0, ptr %b_pos, align 4
  store i32 0, ptr %a_size, align 4
  store i32 0, ptr %a_pos, align 4
  br label %sw.epilog

sw.epilog:                                        ; preds = %sw.default, %sw.bb81, %sw.bb80, %sw.bb79, %sw.bb
  %45 = load i32, ptr %r_size, align 4
  %call82 = call i32 (ptr, ...) @printf(ptr noundef @.str.33, i32 noundef %45)
  %46 = load i32, ptr %r_pos, align 4
  %call83 = call i32 (ptr, ...) @printf(ptr noundef @.str.34, i32 noundef %46)
  %47 = load i32, ptr %g_size, align 4
  %call84 = call i32 (ptr, ...) @printf(ptr noundef @.str.35, i32 noundef %47)
  %48 = load i32, ptr %g_pos, align 4
  %call85 = call i32 (ptr, ...) @printf(ptr noundef @.str.36, i32 noundef %48)
  %49 = load i32, ptr %b_size, align 4
  %call86 = call i32 (ptr, ...) @printf(ptr noundef @.str.37, i32 noundef %49)
  %50 = load i32, ptr %b_pos, align 4
  %call87 = call i32 (ptr, ...) @printf(ptr noundef @.str.38, i32 noundef %50)
  %51 = load i32, ptr %a_size, align 4
  %call88 = call i32 (ptr, ...) @printf(ptr noundef @.str.39, i32 noundef %51)
  %52 = load i32, ptr %a_pos, align 4
  %call89 = call i32 (ptr, ...) @printf(ptr noundef @.str.40, i32 noundef %52)
  %53 = load ptr, ptr %pm, align 8
  %depth90 = getelementptr inbounds %struct.ModeInfo, ptr %53, i32 0, i32 2
  %54 = load i32, ptr %depth90, align 4
  %cmp91 = icmp eq i32 %54, 32
  br i1 %cmp91, label %if.then93, label %if.else95

if.then93:                                        ; preds = %sw.epilog
  %call94 = call i32 (ptr, ...) @printf(ptr noundef @.str.41, ptr noundef @.str.42)
  br label %if.end97

if.else95:                                        ; preds = %sw.epilog
  %call96 = call i32 (ptr, ...) @printf(ptr noundef @.str.41, ptr noundef @.str.43)
  br label %if.end97

if.end97:                                         ; preds = %if.else95, %if.then93
  %55 = load ptr, ptr %pm, align 8
  %depth98 = getelementptr inbounds %struct.ModeInfo, ptr %55, i32 0, i32 2
  %56 = load i32, ptr %depth98, align 4
  %cmp99 = icmp sgt i32 %56, 4
  br i1 %cmp99, label %if.then101, label %if.else103

if.then101:                                       ; preds = %if.end97
  %call102 = call i32 (ptr, ...) @printf(ptr noundef @.str.44, ptr noundef @.str.45)
  br label %if.end105

if.else103:                                       ; preds = %if.end97
  %call104 = call i32 (ptr, ...) @printf(ptr noundef @.str.44, ptr noundef @.str.43)
  br label %if.end105

if.end105:                                        ; preds = %if.else103, %if.then101
  %call106 = call i32 (ptr, ...) @printf(ptr noundef @.str.46, i32 noundef 0)
  %call107 = call i32 (ptr, ...) @printf(ptr noundef @.str.47, i32 noundef 0)
  %57 = load i32, ptr %pitch, align 4
  %call108 = call i32 (ptr, ...) @printf(ptr noundef @.str.48, i32 noundef %57)
  %call109 = call i32 (ptr, ...) @printf(ptr noundef @.str.49, i32 noundef 0)
  %call110 = call i32 (ptr, ...) @printf(ptr noundef @.str.50, i32 noundef 0)
  %58 = load i32, ptr %r_size, align 4
  %call111 = call i32 (ptr, ...) @printf(ptr noundef @.str.51, i32 noundef %58)
  %59 = load i32, ptr %r_pos, align 4
  %call112 = call i32 (ptr, ...) @printf(ptr noundef @.str.52, i32 noundef %59)
  %60 = load i32, ptr %g_size, align 4
  %call113 = call i32 (ptr, ...) @printf(ptr noundef @.str.53, i32 noundef %60)
  %61 = load i32, ptr %g_pos, align 4
  %call114 = call i32 (ptr, ...) @printf(ptr noundef @.str.54, i32 noundef %61)
  %62 = load i32, ptr %b_size, align 4
  %call115 = call i32 (ptr, ...) @printf(ptr noundef @.str.55, i32 noundef %62)
  %63 = load i32, ptr %b_pos, align 4
  %call116 = call i32 (ptr, ...) @printf(ptr noundef @.str.56, i32 noundef %63)
  %64 = load i32, ptr %a_size, align 4
  %call117 = call i32 (ptr, ...) @printf(ptr noundef @.str.57, i32 noundef %64)
  %65 = load i32, ptr %a_pos, align 4
  %call118 = call i32 (ptr, ...) @printf(ptr noundef @.str.58, i32 noundef %65)
  %call119 = call i32 (ptr, ...) @printf(ptr noundef @.str.59, i32 noundef 0)
  %call120 = call i32 (ptr, ...) @printf(ptr noundef @.str.60)
  br label %if.end121

if.end121:                                        ; preds = %if.end105, %if.end
  br label %for.inc

for.inc:                                          ; preds = %if.end121
  %66 = load ptr, ptr %pm, align 8
  %incdec.ptr = getelementptr inbounds %struct.ModeInfo, ptr %66, i32 1
  store ptr %incdec.ptr, ptr %pm, align 8
  br label %for.cond, !llvm.loop !5

for.end:                                          ; preds = %for.cond
  %call122 = call i32 (ptr, ...) @printf(ptr noundef @.str.61)
  %call123 = call i32 (ptr, ...) @printf(ptr noundef @.str.62)
  %call124 = call i32 (ptr, ...) @printf(ptr noundef @.str.60)
  %call125 = call i32 (ptr, ...) @printf(ptr noundef @.str.63)
  ret i32 0
}

declare i32 @printf(ptr noundef, ...) #1

attributes #0 = { noinline nounwind optnone ssp uwtable(sync) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="apple-m1" "target-features"="+aes,+altnzcv,+ccdp,+ccidx,+complxnum,+crc,+dit,+dotprod,+flagm,+fp-armv8,+fp16fml,+fptoint,+fullfp16,+jsconv,+lse,+neon,+pauth,+perfmon,+predres,+ras,+rcpc,+rdm,+sb,+sha2,+sha3,+specrestrict,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8a,+zcm,+zcz" }
attributes #1 = { "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="apple-m1" "target-features"="+aes,+altnzcv,+ccdp,+ccidx,+complxnum,+crc,+dit,+dotprod,+flagm,+fp-armv8,+fp16fml,+fptoint,+fullfp16,+jsconv,+lse,+neon,+pauth,+perfmon,+predres,+ras,+rcpc,+rdm,+sb,+sha2,+sha3,+specrestrict,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8a,+zcm,+zcz" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"uwtable", i32 1}
!3 = !{i32 7, !"frame-pointer", i32 1}
!4 = !{!"Homebrew clang version 19.1.4"}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.mustprogress"}
