; ModuleID = 'code/033-16155vbetables-gen.c'
source_filename = "code/033-16155vbetables-gen.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.ModeInfo = type { i32, i32, i32, i32 }

@modes = dso_local global [37 x %struct.ModeInfo] [%struct.ModeInfo { i32 640, i32 400, i32 8, i32 256 }, %struct.ModeInfo { i32 640, i32 480, i32 8, i32 257 }, %struct.ModeInfo { i32 800, i32 600, i32 4, i32 258 }, %struct.ModeInfo { i32 800, i32 600, i32 8, i32 259 }, %struct.ModeInfo { i32 1024, i32 768, i32 4, i32 260 }, %struct.ModeInfo { i32 1024, i32 768, i32 8, i32 261 }, %struct.ModeInfo { i32 1280, i32 1024, i32 4, i32 262 }, %struct.ModeInfo { i32 1280, i32 1024, i32 8, i32 263 }, %struct.ModeInfo { i32 320, i32 200, i32 15, i32 269 }, %struct.ModeInfo { i32 320, i32 200, i32 16, i32 270 }, %struct.ModeInfo { i32 320, i32 200, i32 24, i32 271 }, %struct.ModeInfo { i32 640, i32 480, i32 15, i32 272 }, %struct.ModeInfo { i32 640, i32 480, i32 16, i32 273 }, %struct.ModeInfo { i32 640, i32 480, i32 24, i32 274 }, %struct.ModeInfo { i32 800, i32 600, i32 15, i32 275 }, %struct.ModeInfo { i32 800, i32 600, i32 16, i32 276 }, %struct.ModeInfo { i32 800, i32 600, i32 24, i32 277 }, %struct.ModeInfo { i32 1024, i32 768, i32 15, i32 278 }, %struct.ModeInfo { i32 1024, i32 768, i32 16, i32 279 }, %struct.ModeInfo { i32 1024, i32 768, i32 24, i32 280 }, %struct.ModeInfo { i32 1280, i32 1024, i32 15, i32 281 }, %struct.ModeInfo { i32 1280, i32 1024, i32 16, i32 282 }, %struct.ModeInfo { i32 1280, i32 1024, i32 24, i32 283 }, %struct.ModeInfo { i32 320, i32 200, i32 32, i32 320 }, %struct.ModeInfo { i32 640, i32 400, i32 32, i32 321 }, %struct.ModeInfo { i32 640, i32 480, i32 32, i32 322 }, %struct.ModeInfo { i32 800, i32 600, i32 32, i32 323 }, %struct.ModeInfo { i32 1024, i32 768, i32 32, i32 324 }, %struct.ModeInfo { i32 1280, i32 1024, i32 32, i32 325 }, %struct.ModeInfo { i32 320, i32 200, i32 8, i32 326 }, %struct.ModeInfo { i32 1600, i32 1200, i32 32, i32 327 }, %struct.ModeInfo { i32 1152, i32 864, i32 8, i32 328 }, %struct.ModeInfo { i32 1152, i32 864, i32 15, i32 329 }, %struct.ModeInfo { i32 1152, i32 864, i32 16, i32 330 }, %struct.ModeInfo { i32 1152, i32 864, i32 24, i32 331 }, %struct.ModeInfo { i32 1152, i32 864, i32 32, i32 332 }, %struct.ModeInfo zeroinitializer], align 16
@.str = private unnamed_addr constant [59 x i8] c"/* THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT */\0A\0A\00", align 1
@.str.1 = private unnamed_addr constant [45 x i8] c"#define VBE_DISPI_TOTAL_VIDEO_MEMORY_MB %d\0A\0A\00", align 1
@.str.2 = private unnamed_addr constant [43 x i8] c"static ModeInfoListItem mode_info_list[]=\0A\00", align 1
@.str.3 = private unnamed_addr constant [3 x i8] c"{\0A\00", align 1
@.str.4 = private unnamed_addr constant [26 x i8] c"{ 0x%04x, /* %dx%dx%d */\0A\00", align 1
@.str.5 = private unnamed_addr constant [33 x i8] c"{ /*Bit16u ModeAttributes*/ %s,\0A\00", align 1
@.str.6 = private unnamed_addr constant [186 x i8] c"VBE_MODE_ATTRIBUTE_SUPPORTED | VBE_MODE_ATTRIBUTE_EXTENDED_INFORMATION_AVAILABLE | VBE_MODE_ATTRIBUTE_COLOR_MODE | VBE_MODE_ATTRIBUTE_TTY_BIOS_SUPPORT | VBE_MODE_ATTRIBUTE_GRAPHICS_MODE\00", align 1
@.str.7 = private unnamed_addr constant [194 x i8] c"VBE_MODE_ATTRIBUTE_SUPPORTED | VBE_MODE_ATTRIBUTE_EXTENDED_INFORMATION_AVAILABLE | VBE_MODE_ATTRIBUTE_COLOR_MODE | VBE_MODE_ATTRIBUTE_LINEAR_FRAME_BUFFER_MODE | VBE_MODE_ATTRIBUTE_GRAPHICS_MODE\00", align 1
@.str.8 = private unnamed_addr constant [31 x i8] c"/*Bit8u  WinAAttributes*/ %s,\0A\00", align 1
@.str.9 = private unnamed_addr constant [98 x i8] c"VBE_WINDOW_ATTRIBUTE_RELOCATABLE | VBE_WINDOW_ATTRIBUTE_READABLE | VBE_WINDOW_ATTRIBUTE_WRITEABLE\00", align 1
@.str.10 = private unnamed_addr constant [31 x i8] c"/*Bit8u  WinBAttributes*/ %d,\0A\00", align 1
@.str.11 = private unnamed_addr constant [31 x i8] c"/*Bit16u WinGranularity*/ %s,\0A\00", align 1
@.str.12 = private unnamed_addr constant [23 x i8] c"VBE_DISPI_BANK_SIZE_KB\00", align 1
@.str.13 = private unnamed_addr constant [24 x i8] c"/*Bit16u WinSize*/ %s,\0A\00", align 1
@.str.14 = private unnamed_addr constant [28 x i8] c"/*Bit16u WinASegment*/ %s,\0A\00", align 1
@.str.15 = private unnamed_addr constant [13 x i8] c"VGAMEM_GRAPH\00", align 1
@.str.16 = private unnamed_addr constant [32 x i8] c"/*Bit16u WinBSegment*/ 0x%04x,\0A\00", align 1
@.str.17 = private unnamed_addr constant [27 x i8] c"/*Bit32u WinFuncPtr*/ %d,\0A\00", align 1
@.str.18 = private unnamed_addr constant [33 x i8] c"/*Bit16u BytesPerScanLine*/ %d,\0A\00", align 1
@.str.19 = private unnamed_addr constant [28 x i8] c"/*Bit16u XResolution*/ %d,\0A\00", align 1
@.str.20 = private unnamed_addr constant [28 x i8] c"/*Bit16u YResolution*/ %d,\0A\00", align 1
@.str.21 = private unnamed_addr constant [26 x i8] c"/*Bit8u  XCharSize*/ %d,\0A\00", align 1
@.str.22 = private unnamed_addr constant [26 x i8] c"/*Bit8u  YCharSize*/ %d,\0A\00", align 1
@.str.23 = private unnamed_addr constant [31 x i8] c"/*Bit8u  NumberOfPlanes*/ %d,\0A\00", align 1
@.str.24 = private unnamed_addr constant [29 x i8] c"/*Bit8u  BitsPerPixel*/ %d,\0A\00", align 1
@.str.25 = private unnamed_addr constant [30 x i8] c"/*Bit8u  NumberOfBanks*/ %d,\0A\00", align 1
@.str.26 = private unnamed_addr constant [23 x i8] c"VBE_MEMORYMODEL_PLANAR\00", align 1
@.str.27 = private unnamed_addr constant [29 x i8] c"VBE_MEMORYMODEL_PACKED_PIXEL\00", align 1
@.str.28 = private unnamed_addr constant [29 x i8] c"VBE_MEMORYMODEL_DIRECT_COLOR\00", align 1
@.str.29 = private unnamed_addr constant [28 x i8] c"/*Bit8u  MemoryModel*/ %s,\0A\00", align 1
@.str.30 = private unnamed_addr constant [25 x i8] c"/*Bit8u  BankSize*/ %d,\0A\00", align 1
@.str.31 = private unnamed_addr constant [35 x i8] c"/*Bit8u  NumberOfImagePages*/ %d,\0A\00", align 1
@.str.32 = private unnamed_addr constant [30 x i8] c"/*Bit8u  Reserved_page*/ %d,\0A\00", align 1
@.str.33 = private unnamed_addr constant [28 x i8] c"/*Bit8u  RedMaskSize*/ %d,\0A\00", align 1
@.str.34 = private unnamed_addr constant [33 x i8] c"/*Bit8u  RedFieldPosition*/ %d,\0A\00", align 1
@.str.35 = private unnamed_addr constant [30 x i8] c"/*Bit8u  GreenMaskSize*/ %d,\0A\00", align 1
@.str.36 = private unnamed_addr constant [35 x i8] c"/*Bit8u  GreenFieldPosition*/ %d,\0A\00", align 1
@.str.37 = private unnamed_addr constant [29 x i8] c"/*Bit8u  BlueMaskSize*/ %d,\0A\00", align 1
@.str.38 = private unnamed_addr constant [34 x i8] c"/*Bit8u  BlueFieldPosition*/ %d,\0A\00", align 1
@.str.39 = private unnamed_addr constant [29 x i8] c"/*Bit8u  RsvdMaskSize*/ %d,\0A\00", align 1
@.str.40 = private unnamed_addr constant [34 x i8] c"/*Bit8u  RsvdFieldPosition*/ %d,\0A\00", align 1
@.str.41 = private unnamed_addr constant [36 x i8] c"/*Bit8u  DirectColorModeInfo*/ %s,\0A\00", align 1
@.str.42 = private unnamed_addr constant [40 x i8] c"VBE_DIRECTCOLOR_RESERVED_BITS_AVAILABLE\00", align 1
@.str.43 = private unnamed_addr constant [2 x i8] c"0\00", align 1
@.str.44 = private unnamed_addr constant [28 x i8] c"/*Bit32u PhysBasePtr*/ %s,\0A\00", align 1
@.str.45 = private unnamed_addr constant [31 x i8] c"VBE_DISPI_LFB_PHYSICAL_ADDRESS\00", align 1
@.str.46 = private unnamed_addr constant [35 x i8] c"/*Bit32u OffScreenMemOffset*/ %d,\0A\00", align 1
@.str.47 = private unnamed_addr constant [33 x i8] c"/*Bit16u OffScreenMemSize*/ %d,\0A\00", align 1
@.str.48 = private unnamed_addr constant [36 x i8] c"/*Bit16u LinBytesPerScanLine*/ %d,\0A\00", align 1
@.str.49 = private unnamed_addr constant [33 x i8] c"/*Bit8u  BnkNumberOfPages*/ %d,\0A\00", align 1
@.str.50 = private unnamed_addr constant [33 x i8] c"/*Bit8u  LinNumberOfPages*/ %d,\0A\00", align 1
@.str.51 = private unnamed_addr constant [31 x i8] c"/*Bit8u  LinRedMaskSize*/ %d,\0A\00", align 1
@.str.52 = private unnamed_addr constant [36 x i8] c"/*Bit8u  LinRedFieldPosition*/ %d,\0A\00", align 1
@.str.53 = private unnamed_addr constant [33 x i8] c"/*Bit8u  LinGreenMaskSize*/ %d,\0A\00", align 1
@.str.54 = private unnamed_addr constant [38 x i8] c"/*Bit8u  LinGreenFieldPosition*/ %d,\0A\00", align 1
@.str.55 = private unnamed_addr constant [32 x i8] c"/*Bit8u  LinBlueMaskSize*/ %d,\0A\00", align 1
@.str.56 = private unnamed_addr constant [37 x i8] c"/*Bit8u  LinBlueFieldPosition*/ %d,\0A\00", align 1
@.str.57 = private unnamed_addr constant [32 x i8] c"/*Bit8u  LinRsvdMaskSize*/ %d,\0A\00", align 1
@.str.58 = private unnamed_addr constant [37 x i8] c"/*Bit8u  LinRsvdFieldPosition*/ %d,\0A\00", align 1
@.str.59 = private unnamed_addr constant [30 x i8] c"/*Bit32u MaxPixelClock*/ %d,\0A\00", align 1
@.str.60 = private unnamed_addr constant [6 x i8] c"} },\0A\00", align 1
@.str.61 = private unnamed_addr constant [30 x i8] c"{ VBE_VESA_MODE_END_OF_LIST,\0A\00", align 1
@.str.62 = private unnamed_addr constant [6 x i8] c"{ 0,\0A\00", align 1
@.str.63 = private unnamed_addr constant [4 x i8] c"};\0A\00", align 1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main(i32 %argc, i8** %argv) #0 {
entry:
  %retval = alloca i32, align 4
  %argc.addr = alloca i32, align 4
  %argv.addr = alloca i8**, align 8
  %pm = alloca %struct.ModeInfo*, align 8
  %pages = alloca i32, align 4
  %pitch = alloca i32, align 4
  %r_size = alloca i32, align 4
  %r_pos = alloca i32, align 4
  %g_size = alloca i32, align 4
  %g_pos = alloca i32, align 4
  %b_size = alloca i32, align 4
  %b_pos = alloca i32, align 4
  %a_size = alloca i32, align 4
  %a_pos = alloca i32, align 4
  %str = alloca i8*, align 8
  %vram_size = alloca i64, align 8
  store i32 0, i32* %retval, align 4
  store i32 %argc, i32* %argc.addr, align 4
  store i8** %argv, i8*** %argv.addr, align 8
  store i64 8388608, i64* %vram_size, align 8
  %call = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([59 x i8], [59 x i8]* @.str, i64 0, i64 0))
  %call1 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([45 x i8], [45 x i8]* @.str.1, i64 0, i64 0), i32 8)
  %call2 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([43 x i8], [43 x i8]* @.str.2, i64 0, i64 0))
  %call3 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str.3, i64 0, i64 0))
  store %struct.ModeInfo* getelementptr inbounds ([37 x %struct.ModeInfo], [37 x %struct.ModeInfo]* @modes, i64 0, i64 0), %struct.ModeInfo** %pm, align 8
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %mode = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %0, i32 0, i32 3
  %1 = load i32, i32* %mode, align 4
  %cmp = icmp ne i32 %1, 0
  br i1 %cmp, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %2 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %2, i32 0, i32 2
  %3 = load i32, i32* %depth, align 4
  %cmp4 = icmp eq i32 %3, 4
  br i1 %cmp4, label %if.then, label %if.else

if.then:                                          ; preds = %for.body
  %4 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %width = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %4, i32 0, i32 0
  %5 = load i32, i32* %width, align 4
  %add = add nsw i32 %5, 7
  %div = sdiv i32 %add, 8
  store i32 %div, i32* %pitch, align 4
  br label %if.end

if.else:                                          ; preds = %for.body
  %6 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %width5 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %6, i32 0, i32 0
  %7 = load i32, i32* %width5, align 4
  %8 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth6 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %8, i32 0, i32 2
  %9 = load i32, i32* %depth6, align 4
  %add7 = add nsw i32 %9, 7
  %div8 = sdiv i32 %add7, 8
  %mul = mul nsw i32 %7, %div8
  store i32 %mul, i32* %pitch, align 4
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %10 = load i64, i64* %vram_size, align 8
  %11 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %height = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %11, i32 0, i32 1
  %12 = load i32, i32* %height, align 4
  %13 = load i32, i32* %pitch, align 4
  %mul9 = mul nsw i32 %12, %13
  %conv = sext i32 %mul9 to i64
  %div10 = sdiv i64 %10, %conv
  %conv11 = trunc i64 %div10 to i32
  store i32 %conv11, i32* %pages, align 4
  %14 = load i32, i32* %pages, align 4
  %cmp12 = icmp sgt i32 %14, 0
  br i1 %cmp12, label %if.then14, label %if.end121

if.then14:                                        ; preds = %if.end
  %15 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %mode15 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %15, i32 0, i32 3
  %16 = load i32, i32* %mode15, align 4
  %17 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %width16 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %17, i32 0, i32 0
  %18 = load i32, i32* %width16, align 4
  %19 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %height17 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %19, i32 0, i32 1
  %20 = load i32, i32* %height17, align 4
  %21 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth18 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %21, i32 0, i32 2
  %22 = load i32, i32* %depth18, align 4
  %call19 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([26 x i8], [26 x i8]* @.str.4, i64 0, i64 0), i32 %16, i32 %18, i32 %20, i32 %22)
  %23 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth20 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %23, i32 0, i32 2
  %24 = load i32, i32* %depth20, align 4
  %cmp21 = icmp eq i32 %24, 4
  br i1 %cmp21, label %if.then23, label %if.else25

if.then23:                                        ; preds = %if.then14
  %call24 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.5, i64 0, i64 0), i8* getelementptr inbounds ([186 x i8], [186 x i8]* @.str.6, i64 0, i64 0))
  br label %if.end27

if.else25:                                        ; preds = %if.then14
  %call26 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.5, i64 0, i64 0), i8* getelementptr inbounds ([194 x i8], [194 x i8]* @.str.7, i64 0, i64 0))
  br label %if.end27

if.end27:                                         ; preds = %if.else25, %if.then23
  %call28 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.8, i64 0, i64 0), i8* getelementptr inbounds ([98 x i8], [98 x i8]* @.str.9, i64 0, i64 0))
  %call29 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.10, i64 0, i64 0), i32 0)
  %call30 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.11, i64 0, i64 0), i8* getelementptr inbounds ([23 x i8], [23 x i8]* @.str.12, i64 0, i64 0))
  %call31 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([24 x i8], [24 x i8]* @.str.13, i64 0, i64 0), i8* getelementptr inbounds ([23 x i8], [23 x i8]* @.str.12, i64 0, i64 0))
  %call32 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.14, i64 0, i64 0), i8* getelementptr inbounds ([13 x i8], [13 x i8]* @.str.15, i64 0, i64 0))
  %call33 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @.str.16, i64 0, i64 0), i32 0)
  %call34 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([27 x i8], [27 x i8]* @.str.17, i64 0, i64 0), i32 0)
  %25 = load i32, i32* %pitch, align 4
  %call35 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.18, i64 0, i64 0), i32 %25)
  %26 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %width36 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %26, i32 0, i32 0
  %27 = load i32, i32* %width36, align 4
  %call37 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.19, i64 0, i64 0), i32 %27)
  %28 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %height38 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %28, i32 0, i32 1
  %29 = load i32, i32* %height38, align 4
  %call39 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.20, i64 0, i64 0), i32 %29)
  %call40 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([26 x i8], [26 x i8]* @.str.21, i64 0, i64 0), i32 8)
  %call41 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([26 x i8], [26 x i8]* @.str.22, i64 0, i64 0), i32 16)
  %30 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth42 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %30, i32 0, i32 2
  %31 = load i32, i32* %depth42, align 4
  %cmp43 = icmp eq i32 %31, 4
  br i1 %cmp43, label %if.then45, label %if.else47

if.then45:                                        ; preds = %if.end27
  %call46 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.23, i64 0, i64 0), i32 4)
  br label %if.end49

if.else47:                                        ; preds = %if.end27
  %call48 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.23, i64 0, i64 0), i32 1)
  br label %if.end49

if.end49:                                         ; preds = %if.else47, %if.then45
  %32 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth50 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %32, i32 0, i32 2
  %33 = load i32, i32* %depth50, align 4
  %call51 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([29 x i8], [29 x i8]* @.str.24, i64 0, i64 0), i32 %33)
  %call52 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @.str.25, i64 0, i64 0), i32 1)
  %34 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth53 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %34, i32 0, i32 2
  %35 = load i32, i32* %depth53, align 4
  %cmp54 = icmp eq i32 %35, 4
  br i1 %cmp54, label %if.then56, label %if.else57

if.then56:                                        ; preds = %if.end49
  store i8* getelementptr inbounds ([23 x i8], [23 x i8]* @.str.26, i64 0, i64 0), i8** %str, align 8
  br label %if.end64

if.else57:                                        ; preds = %if.end49
  %36 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth58 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %36, i32 0, i32 2
  %37 = load i32, i32* %depth58, align 4
  %cmp59 = icmp eq i32 %37, 8
  br i1 %cmp59, label %if.then61, label %if.else62

if.then61:                                        ; preds = %if.else57
  store i8* getelementptr inbounds ([29 x i8], [29 x i8]* @.str.27, i64 0, i64 0), i8** %str, align 8
  br label %if.end63

if.else62:                                        ; preds = %if.else57
  store i8* getelementptr inbounds ([29 x i8], [29 x i8]* @.str.28, i64 0, i64 0), i8** %str, align 8
  br label %if.end63

if.end63:                                         ; preds = %if.else62, %if.then61
  br label %if.end64

if.end64:                                         ; preds = %if.end63, %if.then56
  %38 = load i8*, i8** %str, align 8
  %call65 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.29, i64 0, i64 0), i8* %38)
  %call66 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str.30, i64 0, i64 0), i32 0)
  %39 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth67 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %39, i32 0, i32 2
  %40 = load i32, i32* %depth67, align 4
  %cmp68 = icmp eq i32 %40, 4
  br i1 %cmp68, label %if.then70, label %if.else73

if.then70:                                        ; preds = %if.end64
  %41 = load i32, i32* %pages, align 4
  %div71 = sdiv i32 %41, 4
  %sub = sub nsw i32 %div71, 1
  %call72 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([35 x i8], [35 x i8]* @.str.31, i64 0, i64 0), i32 %sub)
  br label %if.end76

if.else73:                                        ; preds = %if.end64
  %42 = load i32, i32* %pages, align 4
  %sub74 = sub nsw i32 %42, 1
  %call75 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([35 x i8], [35 x i8]* @.str.31, i64 0, i64 0), i32 %sub74)
  br label %if.end76

if.end76:                                         ; preds = %if.else73, %if.then70
  %call77 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @.str.32, i64 0, i64 0), i32 0)
  %43 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth78 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %43, i32 0, i32 2
  %44 = load i32, i32* %depth78, align 4
  switch i32 %44, label %sw.default [
    i32 15, label %sw.bb
    i32 16, label %sw.bb79
    i32 24, label %sw.bb80
    i32 32, label %sw.bb81
  ]

sw.bb:                                            ; preds = %if.end76
  store i32 5, i32* %r_size, align 4
  store i32 10, i32* %r_pos, align 4
  store i32 5, i32* %g_size, align 4
  store i32 5, i32* %g_pos, align 4
  store i32 5, i32* %b_size, align 4
  store i32 0, i32* %b_pos, align 4
  store i32 1, i32* %a_size, align 4
  store i32 15, i32* %a_pos, align 4
  br label %sw.epilog

sw.bb79:                                          ; preds = %if.end76
  store i32 5, i32* %r_size, align 4
  store i32 11, i32* %r_pos, align 4
  store i32 6, i32* %g_size, align 4
  store i32 5, i32* %g_pos, align 4
  store i32 5, i32* %b_size, align 4
  store i32 0, i32* %b_pos, align 4
  store i32 0, i32* %a_size, align 4
  store i32 0, i32* %a_pos, align 4
  br label %sw.epilog

sw.bb80:                                          ; preds = %if.end76
  store i32 8, i32* %r_size, align 4
  store i32 16, i32* %r_pos, align 4
  store i32 8, i32* %g_size, align 4
  store i32 8, i32* %g_pos, align 4
  store i32 8, i32* %b_size, align 4
  store i32 0, i32* %b_pos, align 4
  store i32 0, i32* %a_size, align 4
  store i32 0, i32* %a_pos, align 4
  br label %sw.epilog

sw.bb81:                                          ; preds = %if.end76
  store i32 8, i32* %r_size, align 4
  store i32 16, i32* %r_pos, align 4
  store i32 8, i32* %g_size, align 4
  store i32 8, i32* %g_pos, align 4
  store i32 8, i32* %b_size, align 4
  store i32 0, i32* %b_pos, align 4
  store i32 8, i32* %a_size, align 4
  store i32 24, i32* %a_pos, align 4
  br label %sw.epilog

sw.default:                                       ; preds = %if.end76
  store i32 0, i32* %r_size, align 4
  store i32 0, i32* %r_pos, align 4
  store i32 0, i32* %g_size, align 4
  store i32 0, i32* %g_pos, align 4
  store i32 0, i32* %b_size, align 4
  store i32 0, i32* %b_pos, align 4
  store i32 0, i32* %a_size, align 4
  store i32 0, i32* %a_pos, align 4
  br label %sw.epilog

sw.epilog:                                        ; preds = %sw.default, %sw.bb81, %sw.bb80, %sw.bb79, %sw.bb
  %45 = load i32, i32* %r_size, align 4
  %call82 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.33, i64 0, i64 0), i32 %45)
  %46 = load i32, i32* %r_pos, align 4
  %call83 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.34, i64 0, i64 0), i32 %46)
  %47 = load i32, i32* %g_size, align 4
  %call84 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @.str.35, i64 0, i64 0), i32 %47)
  %48 = load i32, i32* %g_pos, align 4
  %call85 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([35 x i8], [35 x i8]* @.str.36, i64 0, i64 0), i32 %48)
  %49 = load i32, i32* %b_size, align 4
  %call86 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([29 x i8], [29 x i8]* @.str.37, i64 0, i64 0), i32 %49)
  %50 = load i32, i32* %b_pos, align 4
  %call87 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([34 x i8], [34 x i8]* @.str.38, i64 0, i64 0), i32 %50)
  %51 = load i32, i32* %a_size, align 4
  %call88 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([29 x i8], [29 x i8]* @.str.39, i64 0, i64 0), i32 %51)
  %52 = load i32, i32* %a_pos, align 4
  %call89 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([34 x i8], [34 x i8]* @.str.40, i64 0, i64 0), i32 %52)
  %53 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth90 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %53, i32 0, i32 2
  %54 = load i32, i32* %depth90, align 4
  %cmp91 = icmp eq i32 %54, 32
  br i1 %cmp91, label %if.then93, label %if.else95

if.then93:                                        ; preds = %sw.epilog
  %call94 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.str.41, i64 0, i64 0), i8* getelementptr inbounds ([40 x i8], [40 x i8]* @.str.42, i64 0, i64 0))
  br label %if.end97

if.else95:                                        ; preds = %sw.epilog
  %call96 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.str.41, i64 0, i64 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.str.43, i64 0, i64 0))
  br label %if.end97

if.end97:                                         ; preds = %if.else95, %if.then93
  %55 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %depth98 = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %55, i32 0, i32 2
  %56 = load i32, i32* %depth98, align 4
  %cmp99 = icmp sgt i32 %56, 4
  br i1 %cmp99, label %if.then101, label %if.else103

if.then101:                                       ; preds = %if.end97
  %call102 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.44, i64 0, i64 0), i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.45, i64 0, i64 0))
  br label %if.end105

if.else103:                                       ; preds = %if.end97
  %call104 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([28 x i8], [28 x i8]* @.str.44, i64 0, i64 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.str.43, i64 0, i64 0))
  br label %if.end105

if.end105:                                        ; preds = %if.else103, %if.then101
  %call106 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([35 x i8], [35 x i8]* @.str.46, i64 0, i64 0), i32 0)
  %call107 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.47, i64 0, i64 0), i32 0)
  %57 = load i32, i32* %pitch, align 4
  %call108 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.str.48, i64 0, i64 0), i32 %57)
  %call109 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.49, i64 0, i64 0), i32 0)
  %call110 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.50, i64 0, i64 0), i32 0)
  %58 = load i32, i32* %r_size, align 4
  %call111 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([31 x i8], [31 x i8]* @.str.51, i64 0, i64 0), i32 %58)
  %59 = load i32, i32* %r_pos, align 4
  %call112 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.str.52, i64 0, i64 0), i32 %59)
  %60 = load i32, i32* %g_size, align 4
  %call113 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([33 x i8], [33 x i8]* @.str.53, i64 0, i64 0), i32 %60)
  %61 = load i32, i32* %g_pos, align 4
  %call114 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([38 x i8], [38 x i8]* @.str.54, i64 0, i64 0), i32 %61)
  %62 = load i32, i32* %b_size, align 4
  %call115 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @.str.55, i64 0, i64 0), i32 %62)
  %63 = load i32, i32* %b_pos, align 4
  %call116 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([37 x i8], [37 x i8]* @.str.56, i64 0, i64 0), i32 %63)
  %64 = load i32, i32* %a_size, align 4
  %call117 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @.str.57, i64 0, i64 0), i32 %64)
  %65 = load i32, i32* %a_pos, align 4
  %call118 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([37 x i8], [37 x i8]* @.str.58, i64 0, i64 0), i32 %65)
  %call119 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @.str.59, i64 0, i64 0), i32 0)
  %call120 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.60, i64 0, i64 0))
  br label %if.end121

if.end121:                                        ; preds = %if.end105, %if.end
  br label %for.inc

for.inc:                                          ; preds = %if.end121
  %66 = load %struct.ModeInfo*, %struct.ModeInfo** %pm, align 8
  %incdec.ptr = getelementptr inbounds %struct.ModeInfo, %struct.ModeInfo* %66, i32 1
  store %struct.ModeInfo* %incdec.ptr, %struct.ModeInfo** %pm, align 8
  br label %for.cond, !llvm.loop !4

for.end:                                          ; preds = %for.cond
  %call122 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([30 x i8], [30 x i8]* @.str.61, i64 0, i64 0))
  %call123 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.62, i64 0, i64 0))
  %call124 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.60, i64 0, i64 0))
  %call125 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.63, i64 0, i64 0))
  ret i32 0
}

declare dso_local i32 @printf(i8*, ...) #1

attributes #0 = { noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 13.0.0"}
!4 = distinct !{!4, !5}
!5 = !{!"llvm.loop.mustprogress"}
